
spring:
  mandatory-file-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:hsqldb:file:bd
    url: jdbc:jtds:sqlserver://localhost:1433/sed;user=sa;password=Gfhjkm12
    username: sa
    password: twaindoc
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: true


#---
#spring:
#  profiles: init
#  datasource:
#    data: db/data.sql
#---
#spring:
#  profiles: populate
#  datasource:
#    data: db/data_populate.sql









